"""英語の訳。キーは画面に出す日本語の文言(数値が入る文は i18n.trf に渡すテンプレート)。"""

EN = {
    # ---- オープニング ----
    "Eagle 1 の初飛行。操縦するのは、あなただ。": "Eagle 1's first flight. You're the one flying it.",
    "SPACE で点火!": "Press SPACE to ignite!",
    "↑↓ でスロットル(推力)。このエンジンは 70% より下には絞れない。":
        "↑↓ sets the throttle. This engine can't go below 70%.",
    "←→ でノズルを振って姿勢を変える。傾いたら、反対に当てて戻す。":
        "←→ swings the nozzle to steer. If you tilt, counter-steer to come back.",
    "右のウィンドウ: 高度 10 km を通過するとき、この範囲に入っていれば高評価。":
        "The window on the right: be inside these ranges when you pass 10 km for a high rank.",
    "いい調子だ。そのまま、まっすぐ上へ!": "Looking good. Keep going, straight up!",
    "4年前——": "Four years earlier--",
    "すべては、家具もない部屋から始まった。": "It all began in a room without furniture.",

    # ---- 会話: キックオフ ----
    "……で、なんでマリアッチ?": "...So, why a mariachi band?",

    # ---- 会話: ブリーフィング ----
    "よし。俺が飛ばす。": "Right. I'm flying it.",

    # ---- 会話: 結果 ----
    "次は宇宙だ。": "Next stop: space.",
    "……もう払えるお金がないわ。": "...There's no money left to pay anyone.",

    # ---- 会話: 一度だけのエピソード ----
    "俺は絶対に諦めない。文字通り、絶対にだ。": "I will never give up. And I mean never.",

    # ---- 会社の状態 ----
    "創業{year}年目 {month}月": "Year {year}, Month {month}",
    "今月の固定費 {cost:.1f}M$ を払ったわ。残りは {funds:.1f}M$。":
        "Paid this month's fixed costs of {cost:.1f}M$. {funds:.1f}M$ left.",
    "……資金が危ないわ。次の失敗は、会社の終わりかもしれない。":
        "...Our funds are running low. One more failure could end the company.",

    # ---- 会社画面 ----
    "製造": "Build",
    "点検": "Check",
    "調達": "Fund",
    "打上": "Launch",
    "待機": "Wait",
    "次の打ち上げの故障を起きにくくする({cost}M$)": "Make failures less likely on the next launch ({cost}M$)",
    "次の月へ進む": "Advance to next month",
    "製造するお金が足りないわ。": "We don't have enough money to build one.",
    "Eagle 1 の製造を始めたわ。{months}ヶ月後に完成する。":
        "Started building an Eagle 1. It'll be done in {months} months.",
    "点検はもう済んでる。次の打ち上げまで有効よ。": "Already inspected. It holds until the next launch.",
    "{amount}M$ 集まったわ。": "We raised {amount}M$.",
    "資金 {funds:6.1f}M$": "Funds {funds:6.1f}M$",
    "評判 {rep}": "Rep {rep}",
    "機体 {n}{build}": "Rockets {n}{build}",
    " 製造中{n}": " +{n} bldg",
    "製造中": "BUILDING",
    "【{label}】": "[{label}]",
    "←→ 選択 / SPACE・Z 決定": "←→ select / SPACE or Z confirm",

    # ---- 人物 ----
    "ディーロン": "Dylon",
    "マヤ": "Maya",
    "ケン": "Ken",
    "サラ": "Sara",
    "ノア": "Noah",
    "ディーロンAI": "Dylon AI",
    "グレイ": "Grey",
    "ドク・ヒューズ": "Doc Hughes",
    "ボルト": "Bolt",
    "ハシモト": "Hashimoto",
    "ミミ": "Mimi",
    "ゲンさん": "Gen",

    # ---- ミッション ----
    "初飛行": "First Flight",
    "高度 10 km を突破せよ": "Climb past 10 km",
    "時刻": "Time",
    "垂直速度": "V speed",
    "水平速度": "H speed",
    "傾き": "Tilt",
    "window|垂直速度": "V spd",  # 計器パネルの WP の表(幅が狭い)
    "window|水平速度": "H spd",
    "最大動圧を通過": "Passed max Q",
    "エンジン区画で火災! 出力を最低まで絞れ!": "Engine bay fire! Throttle down to minimum!",
    "消火を確認。出力を戻してよし": "Fire is out. Throttle back up.",
    "火災でエンジンが爆発": "Fire blew up the engine",
    "迎角が大きすぎて空中分解": "Broke up: angle of attack too high",
    "姿勢を失ったため飛行中断(自爆)": "Lost attitude: flight terminated",
    "墜落": "Crashed",
    "燃料切れ": "Out of fuel",
    "時間切れ": "Out of time",
    "{name} 通過! 高度 {alt:.0f} km を突破": "{name} passed! Climbed past {alt:.0f} km",

    # ---- 打ち上げ画面 ----
    "射場クリア。カウントダウン開始": "Range clear. Countdown started",
    "点火準備よし。SPACE で点火!": "Ready for ignition. Press SPACE!",
    "点火!": "Ignition!",
    "リフトオフ!": "Liftoff!",
    "SPACE 点火   ↑↓ スロットル   ←→ 姿勢": "SPACE ignite   ↑↓ throttle   ←→ steer",
    "SPACE点火 ↑↓出力 ←→姿勢": "SPACE:ign ↑↓thr ←→steer",
    "!! エンジン火災 !!": "!! ENGINE FIRE !!",
    "WP1 通過 ── ミッション成功": "WP1 PASSED - SUCCESS",
    "ミッション失敗": "MISSION FAILED",
    "ランク {rank}": "Rank {rank}",
    "SPACE で続ける": "SPACE to continue",
    "高度": "Altitude",
    "動圧": "Dyn. Q",
    "角速度": "Rot rate",
    "迎角": "AoA",
    "エンジン": "Engine",
    "燃焼中": "BURN",
    "engine|待機": "IDLE",
    "停止": "OFF",
    "{eng}  点火残 {n}": "{eng}  ignitions {n}",
    "{eng} 点火残{n}": "{eng} ign {n}",
    "スロットル": "Throttle",
    "出力": "Throttle",
    "推進剤": "Fuel",
    "ジンバル": "Gimbal",
    "温度": "Temp",
    "火災!": "FIRE!",
    "{name}  高度 {alt:.0f} km 通過時": "{name}  at {alt:.0f} km altitude",
    "{name}(高度 {alt:.0f} km 通過時)": "{name} (at {alt:.0f} km)",
    "{name} 高度{alt:.0f}km 通過時": "{name} at {alt:.0f} km",
    "ウィンドウに入るほどランクが上がる": "Hit windows to rank up",
    "ウィンドウ内でランクUP": "In window = rank up",

    # ---- リザルト ----
    "ミッション成功": "Mission Success",
    "最高高度 {alt:.2f} km": "Max alt {alt:.2f} km",
    "会社への影響": "Company impact",
    "テレメトリ +{tlm}": "Telemetry +{tlm}",
    "評判 {rep:+d}": "Reputation {rep:+d}",
    "SPACE で工場へ戻る": "SPACE: back to the factory",

    # ---- タイトル ----
    "STAR X  ─  ロケット経営 × 操縦ゲーム": "STAR X  -  rocket company & flight game",
    "企画・原案      airpocket-soundman": "Concept         airpocket-soundman",
    "プログラム      Claude": "Program         Claude",
    "エンジン        Pyxel": "Engine          Pyxel",
    "フォント        umplus(M+ / 東雲)": "Font            umplus (M+ / Shinonome)",
    "実在の宇宙企業へのオマージュ(パロディ)作品です。": "An homage (parody) to real space companies.",
    # ---- 言語と画面の設定 ----
    "言語と画面 / Language & Screen": "Language & Screen",
    "日本語": "日本語",  # 言語の名前はその言語のまま
    "言語 / Language": "Language",
    "画面 / Screen": "Screen",
    "決定 / Start": "Start",
    "↑↓ 選ぶ  ←→ 変える  SPACE 決定": "↑↓ select  ←→ change  SPACE start",
    "X 戻る": "X back",
    "決定すると、この画面サイズで起動し直します。": "The game restarts at this screen size.",

    # ---- 会話(簡素化版) ----
    "創業の日。家具もない借りビルに、なぜかマリアッチ楽団。": "Founding day. A rented building with no furniture, and for some reason, a mariachi band.",
    "キックオフだ! 俺たちは火星に行くんだぞ!": "It's our kickoff! We're going to Mars!",
    "ロケットは高すぎる。材料費は値段の数パーセントだ。なら、自分で作る。":
        "Rockets cost too much. The materials are a few percent of the price. So we build our own.",
    "社員は片手で数えるほど。ここから全部が始まった。": "A handful of people. This is where it all began.",
    "4年後。太平洋の孤島、オメガ島の射場。": "Four years later. The launch site on Omega Island, alone in the Pacific.",
    "資金は 100M$。固定費は毎月 3M$ よ。": "We have 100M$. Fixed costs are 3M$ a month.",
    "Eagle 1 の2号機は組み上がってる。原因を潰せば、いつでも飛ばせるわ。": "Eagle 1 number two is assembled. Fix the cause and it can fly anytime.",
    "Eagle 1 の初飛行は、エンジン火災で空中爆発に終わった。": "Eagle 1's first flight ended in a mid-air explosion after an engine fire.",
    "気に入らーん!!": "I don't like it!!",
    "……まだ説明の途中です。": "...I'm not finished explaining.",
    "初飛行で何が起きるかなんて、誰にもわからん! あと10秒飛ばせば、データが取れるかもしれないんだ!": "Nobody knows what happens on a first flight! Ten more seconds of flying might get us the data!",
    "その判断は俺がする!": "I make that call!",
    "……補足しますと、この人の判断をAIに学ばせます。入力も、視線も、判断までの時間も、全部記録して。": "...To clarify: we'll have an AI learn his judgment. His inputs, his eyes, his reaction times, all recorded.",
    "俺が宇宙船のパイロットだ!": "I'm the spaceship pilot!",
    "……ただ、これから飛ぶたくさんの宇宙船に、全部乗るわけにはいきませんので。": "...Though he can't ride every one of the many ships we'll be flying.",
    "火星に行く船も、俺が飛ばす!": "And I'll fly the ship to Mars, too!",
    "……おっしゃる通りに。": "...Whatever you say.",
    "よし、決まりだ!": "Good, it's settled!",
    "……今の、会話になってた?": "...Was that even a conversation?",
    "ノアが1人で議事録を取ってただけね。": "Noah was just taking the minutes alone.",
    "……本人は、まだ何も聞いていませんけどね。": "...Not that he's heard a word of it.",
    "……燃えちゃったな。4年分が、1分もたたずに。": "...It burned. Four years of work, gone in under a minute.",
    "4年分じゃないわ。図面も、工具も、私たちも残ってる。": "Not four years. The drawings, the tools, and all of us are still here.",
    "おめでとうございます! 素晴らしい試験データが得られました!": "Congratulations! We got some wonderful test data!",
    "……今、おめでとうって言った?": "...Did you just say congratulations?",
    "ノアの言うとおりだ。失敗を恐れて挑戦しないことこそが、本当の失敗だ。": "Noah's right. Not trying because you're afraid to fail: that's the real failure.",
    "何度落ちてもいい。落ちるたびに、俺たちは賢くなる。": "We can crash as many times as it takes. Every crash makes us smarter.",
    "落ちていいのは、お金が尽きるまでよ。": "You can crash until the money runs out. Not after.",
    # ---- ディーロンの一言(ブリーフィング・成功) ----
    "今度は落ちない。……いや、落ちても、また飛ばす。": "This time we won't fall. ...And if we do, we fly again.",
    "宇宙の入口か。ドアはノックするより、蹴り開けるほうが好きだ。": "The edge of space. I'd rather kick that door open than knock.",
    "火星に行くには、まず地球の周りを回れないとな。": "To get to Mars, first we have to go around the Earth.",
    "最後の1機だろうと、いつもと同じように飛ばす。それが一番難しいんだがな。": "Last rocket or not, I fly it like any other. That's the hardest part.",
    "初めてのお客さんだ。荷物は丁寧に、操縦は大胆に。": "Our first customer. Gentle with the cargo, bold on the stick.",
    "9 基か。Eagle 1 の 9 倍、楽しいってことだな。": "Nine engines. Nine times the fun of Eagle 1.",
    "行きより帰りのほうが難しい。宇宙も、人生もな。": "Coming home is harder than leaving. In space, and in life.",
    "ステーションの連中に、民間の運転を見せてやる。……ゆっくりな。": "Let's show the station crew how a private company drives. ...Slowly.",
    "2000 km か。少しずつ、火星に近づいてる気がする。": "Two thousand kilometers. Feels like we're inching toward Mars.",
    "慣れたころが危ない、か。初めての便のつもりで飛ぶ。": "Danger comes when it feels routine. I'll fly it like the first time.",
    "上がって、降りる。それだけのことが、今まで誰にもできなかった。": "Go up, come down. Nobody has ever managed even that.",
    "海の上で止まれたら、次は陸の上で止まれる。一歩ずつだ。": "If we can stop over the sea, we can stop over land. One step at a time.",
    "揺れる甲板に鉛筆を立てる。……燃えてきた。": "Balancing a pencil on a rocking deck. ...Now I'm fired up.",
    "家に帰るのは、いつだっていいもんだ。": "Coming home always feels good.",
    "台船が待ってる。人を待たせるのは趣味じゃない。": "The droneship is waiting. I don't like keeping people waiting.",
    "同じ機体で二度飛ぶ。これができれば、火星への切符が安くなる。": "Fly the same rocket twice. Pull that off, and tickets to Mars get cheaper.",
    "見たか。宇宙は、手の届く場所にある。": "See that? Space is within reach.",
    "まだ飛べる。それで十分だ。": "We can still fly. That's enough.",
    "9 基の炎……たまらないな。": "Nine engines' worth of fire... I love it.",
    "子供の頃に見た未来に、一歩追いついた。": "One step closer to the future I dreamed of as a kid.",
    "静止軌道まで届くなら、商売の地図が全部変わる。": "If we can reach geostationary orbit, the whole business map changes.",
    "倒れても、立ったことには変わりない。": "It fell over, but it still stood up.",
    "嵐の中の鉛筆、立ったぞ!": "The pencil in the storm is standing!",
    "海の上の小さな島か。……オメガ島を思い出すな。": "A tiny island on the sea... Reminds me of Omega Island.",
    # ---- 同じステージで何度も失敗したとき ----
    "おめでとうございます! 前回とは違う、新しい試験データです!": "Congratulations! Brand-new test data, different from last time!",
    "……ノア、それ毎回言うの?": "...Noah, are you going to say that every time?",
    "おめでとうございます! データが、ますます充実してきました!": "Congratulations! Our data keeps getting richer!",
    "お金のほうは、ますます寂しくなってきたけどね。": "Our bank account keeps getting poorer, though.",
    "おめでとうございます! ……正直に言うと、今回は少し言いにくいです。": "Congratulations! ...Honestly, that one is a little hard to say this time.",
    "言え。データはデータだ。": "Say it. Data is data.",
    "おめでとうございます! 同じ落ち方は、もうしていません。前に進んでいます。": "Congratulations! We never crash the same way twice. We're moving forward.",
    "おめでとうございます! この落ち方は、まだ誰も見たことがありません。": "Congratulations! Nobody has ever seen a crash like that before.",
    "見たくなかったよ……。": "I didn't want to see it...",
    "もう一回だ。次は、今回より少しだけうまく飛ぶ。": "One more time. Next time I fly just a little better.",
    "落ちた回数は数えるな。立ち上がった回数を数えろ。": "Don't count how many times we fell. Count how many times we got up.",
    "まだ機体を作れる限り、終わりじゃない。": "As long as we can build another rocket, it's not over.",
    "何度落ちてもいい。最後に一回、飛べばいい。": "Fall as many times as it takes. We only need to fly once, at the end.",
    "前回のデータは頭に入ってる。同じ落ち方はしない。": "Last flight's data is in my head. I won't crash the same way.",
    "今度こそ。……毎回そう言ってるがな。": "This time for sure. ...I say that every time.",
    "失敗はもう十分に集めた。そろそろ成功も集めよう。": "We've collected plenty of failures. Time to collect a success.",
    "深呼吸だ。……よし、行くぞ。": "Deep breath. ...Okay, let's go.",
    "配信のコメント欄、「次がんばれ」で埋まってる。": "The stream chat is full of 'you'll get it next time.'",
    "壊れた部品は全部拾ってきて。全部、先生よ。": "Bring back every broken part. Every one of them is a teacher.",
    "投資家への説明は任せて。「予定どおりの失敗です」って言っておく。": "Leave the investors to me. I'll tell them it was a planned failure.",
    "ログの解析を始めます。原因が分かるまで、そう長くはかかりません。": "Starting log analysis. It won't take long to find the cause.",
    "ロケットは落ちる。落ちないロケットを作るまで、俺たちは落とし続ける。": "Rockets fall. We'll keep dropping them until we build one that doesn't.",
    "爆発の映像、再生数だけはすごいんだよな……。": "The explosion video sure gets a lot of views...",
    "設計を見直すわ。今夜は寝ないから、コーヒーを多めに。": "I'm reviewing the design. No sleep tonight, so extra coffee.",
    "次の飛行の成功確率を、少しだけ上方修正しました。": "I've revised the odds of success on the next flight up, just slightly.",
    "保険の書類、もう書き慣れちゃったわ。": "I've gotten way too good at filling out insurance forms.",
    "誰も笑ってないな。笑え。次は飛ぶんだ。": "Nobody's smiling. Smile. Next time it flies.",
    # ---- 挿絵に重ねる文字 ----
    "全長 21 m": "Length 21 m",
    "2段式": "Two stages",
    "低軌道に 670 kg": "670 kg to low orbit",
    # ---- 軌道への目安(WP)と燃料ボーナス ----
    "WP T+{t:.0f}: 垂直 {vy:.0f} / 水平 {vx:.0f} m/s": "WP T+{t:.0f}: vertical {vy:.0f} / horizontal {vx:.0f} m/s",
    "燃料が残ったぶん、ボーナス {bonus:.1f}M$ よ。": "Fuel left over, so that's a {bonus:.1f}M$ bonus.",
    "資金 +{funds:.1f}M$": "Funds +{funds:.1f}M$",
    "(燃料ボーナス {bonus:.1f}M$)": " (fuel bonus {bonus:.1f}M$)",
    "右の表に、200 秒ごとの目安の速さを出すわ。↑ が垂直、→ が水平。緑なら順調よ。":
        "The panel on the right shows target speeds every 200 seconds. Up arrow is vertical, right arrow is horizontal. Green means on track.",
    "垂直": "Vert",
    "水平": "Horiz",
    "テレメトリも全部残っています。火災の原因は、もう3つまで絞れました。": "We have all the telemetry, too. I've already narrowed the fire down to three causes.",
    "飛行制御は私が——": "I can handle flight control--",
    "却下。俺が飛ばす。": "Denied. I'm flying it.",
    "【操作】←→ で選んで SPACE で決定。「点検」してから「打上」がおすすめ。":
        "[Controls] Choose with ←→ and confirm with SPACE. Try \"Check\" before \"Launch.\"",
    "目標は高度 100 km、宇宙の入口。": "The goal is 100 km, the edge of space.",
    "でも最低でも、発射シーケンスとメインエンジンの燃焼を確かめたいの。高度 10 km を超えれば合格よ。":
        "But at the very least, I want to confirm the launch sequence and the main engine burn. Get past 10 km and we pass.",
    "10 km をウィンドウに入って通過すれば、ランクが上がる。": "Pass 10 km inside the windows for a better rank.",
    "空気が濃いうちは傾けすぎないで。まっすぐ上へ。": "Don't tilt too much while the air is thick. Straight up.",
    "10 km 突破!! 見た!?": "Past 10 km!! Did you see that!?",
    "発射シーケンスも、メインエンジンの燃焼も確認できた。最低限の目標はクリアよ。":
        "Launch sequence and main engine burn, both confirmed. The minimum goal is cleared.",
    "ただ、100 km には届きませんでした。宇宙は、まだ先です。": "We didn't reach 100 km, though. Space is still ahead.",
    "10 km も上がらないなんて……。": "Not even 10 km up...",
    "原因を突き止めて、直してくれ。資金は俺が集める。": "Find the cause and fix it. I'll get the money.",
    "15M$ 集まったわ。……これが最後よ。": "We raised 15M$. ...This is the last chance.",
    "燃料漏れで火が出た。次は「点検」してから飛ばしましょう。": "A fuel leak started a fire. \"Check\" the rocket before the next flight.",
    "空気が濃いところで傾きすぎて、機体が折れたの。まっすぐ、小さく当てて。":
        "It tilted too far in thick air and snapped. Keep it straight, use small inputs.",
    "傾きすぎて自爆したわ。回り始めたら、反対側に当てて止めるの。":
        "It tilted too far and self-destructed. When it starts turning, counter-steer to stop it.",
    "失敗はデータよ。次に活かしましょう。": "Failure is data. Let's use it next time.",
    "今月はもう手一杯。「待機」で次の月へ。": "That's all for this month. \"Wait\" to move on.",
    "資金を集める(3ヶ月に1回)": "Raise money (once every 3 months)",
    "今月はもう動けないわ。「待機」して。": "We can't do more this month. \"Wait.\"",
    "もう2機あるわ。置き場所がない。": "We already have two. No room for more.",
    "調達は3ヶ月に1回までよ。": "Fundraising is once every 3 months.",
    "機体がないわ。「製造」して。": "No rocket. \"Build\" one.",

    # ---- ステージ名と目標 ----
    "Ch1-1 宇宙へ": "Ch1-1 To Space",
    "高度 100 km に到達せよ": "Reach 100 km",
    "Ch1-2 相乗り便": "Ch1-2 Rideshare",
    "小型衛星を軌道に乗せよ": "Put small satellites in orbit",
    "Ch1-3 最後の1機": "Ch1-3 The Last One",
    "ダミー衛星を軌道に乗せよ": "Put a dummy satellite in orbit",
    "Ch1-4 最初の顧客": "Ch1-4 First Customer",
    "観測衛星を円軌道に乗せよ": "Put the satellite in a circular orbit",
    "Ch2-1 Eagle 9 初飛行": "Ch2-1 Eagle 9 Debut",
    "試験カプセルを軌道に乗せよ": "Put the test capsule in orbit",
    "Ch2-2 還ってきたカプセル": "Ch2-2 Capsule Return",
    "カプセルを再突入させ、海に着水させよ": "Reenter and splash down",
    "Ch2-3 民間初の到着": "Ch2-3 First Arrival",
    "ステーションの把持点でカプセルを止めよ": "Stop at the station's grapple point",
    "Ch2-4 初の静止衛星": "Ch2-4 High Orbit",
    "通信衛星を遠地点 2000 km の軌道へ送れ": "Send the satellite to a 2000 km apoapsis",
    "Ch2-5 定期便の試練": "Ch2-5 Routine Trouble",
    "補給カプセルを軌道に乗せよ": "Put the cargo capsule in orbit",
    "Ch3-1 跳ねるバッタ": "Ch3-1 Hopper",
    "100 m まで上がり、隣のパッドに降りよ": "Climb to 100 m, land on the next pad",
    "Ch3-2 海面に立つ": "Ch3-2 On the Sea",
    "1段目を海面の上で静止させよ": "Stop the booster at the sea surface",
    "Ch3-3 台船の試練": "Ch3-3 Droneship",
    "1段目を洋上の台船に降ろせ": "Land the booster on the droneship",
    "Ch3-4 帰ってきた": "Ch3-4 It Came Back",
    "衛星を送り出し、1段目を発射場に戻せ": "Send the satellite, fly the booster back",
    "Ch3-5 海の上の小さな島": "Ch3-5 Island at Sea",
    "補給便を送り出し、1段目を台船に降ろせ": "Send the cargo, land on the droneship",
    "Ch3-6 二度目の空": "Ch3-6 Second Flight",
    "回収した機体で商業衛星を軌道に乗せよ": "Orbit a satellite on a reused booster",

    # ---- 飛行中の通知 ----
    "エンジン停止": "Engine cutoff",
    "もう点火できない": "No ignitions left",
    "先に Z で1段目を分離して": "Separate stage 1 with Z first",
    "1段分離。SPACE で2段目に点火": "Stage 1 separated. SPACE to ignite stage 2",
    "1段分離(自動)。SPACE で2段目に点火": "Stage 1 separated (auto). SPACE to ignite stage 2",
    "1段エンジン停止。推力が消えたら Z で分離": "Stage 1 cutoff. Press Z once the thrust is gone",
    "分離成功。2段目は軌道へ向かった": "Separation good. Stage 2 is heading to orbit",
    "1段目を連れて帰れ。点火はあと {n} 回": "Bring the booster home. {n} ignitions left",
    "放出成功! 軌道投入を確認": "Payload released! Orbit confirmed",
    "パラシュート展開": "Parachute deployed",
    "パラシュートは大気圏に入ってから": "Parachute only after entering the atmosphere",
    "大気圏に突入。耐熱シールドで耐える": "Entering the atmosphere. The heat shield takes it",
    "着水成功! 海面で静止した": "Soft splashdown! It stopped at the surface",
    "着陸成功!": "Landed!",
    "着水成功! カプセルを回収する": "Splashdown! Recovering the capsule",
    "推進剤が揺れている! 逆に当てて姿勢を支えろ": "Fuel slosh! Counter-steer to hold attitude",
    "2段タンクの圧力が異常! Z でカプセルを切り離せ!": "Stage 2 tank pressure anomaly! Press Z to eject the capsule!",
    "エンジン1基停止! 機体が片側へ回る。当て続けて支えろ": "Engine out! It keeps turning one way. Hold counter-steer",
    "アームがカプセルをつかんだ! 到着": "The arm has the capsule! Arrived",
    "ステーションまで 170 m。接近を始める": "170 m to the station. Starting the approach",
    "カウントダウン開始": "Countdown started",

    # ---- 失敗の理由 ----
    "機体は分解。カプセルは脱出して無事": "Vehicle lost. The capsule escaped safely",
    "噴射中に分離して、1段目が追突": "Separated while burning: stage 1 rammed it",
    "残った推力で1段目が追突": "Residual thrust: stage 1 rammed it",
    "回転したまま分離して接触": "Separated while rotating: contact",
    "分離が早すぎて、2段目が軌道に届かない": "Separated too early: stage 2 can't reach orbit",
    "噴射中に放出して衝突": "Released while burning: collision",
    "近地点が低すぎて、荷物は大気圏に落ちた": "Periapsis too low: payload fell into the atmosphere",
    "軌道が目標から外れたまま放出": "Released outside the target orbit",
    "向きがずれたまま放出(投入失敗)": "Released off-axis: insertion failed",
    "回転が残ったまま放出(投入失敗)": "Released while rotating: insertion failed",
    "速すぎるところで開いて、パラシュートが破れた": "Opened too fast: the parachute tore",
    "高度が足りず落下": "Not enough altitude: fell back",
    "軌道に届かず、大気圏に落下": "Missed orbit: fell into the atmosphere",
    "分離しないまま落下": "Fell back without separating",
    "放出の時間切れ": "Release window timed out",
    "軌道が目標から外れた": "Orbit is off target",
    "燃料切れ(軌道に届かず)": "Out of fuel: missed orbit",
    "点火回数を使い切った(軌道に届かず)": "Out of ignitions: missed orbit",
    "高さ 100 m に届かないまま着地": "Landed without reaching 100 m",
    "パッドを外して着地": "Landed off the pad",
    "台船を外して海に落ちた": "Missed the droneship: into the sea",
    "降下が速すぎて、脚が折れた(硬着陸)": "Too fast: legs broke (hard landing)",
    "横に流れたまま接地して転倒": "Drifting at touchdown: tipped over",
    "傾いたまま接地して転倒": "Tilted at touchdown: tipped over",
    "減速が足りず、再突入で機体が分解": "Too fast on reentry: booster broke up",
    "再突入角が浅すぎて、大気に弾かれた": "Entry too shallow: skipped off the atmosphere",
    "耐熱シールドが前を向いていなかった": "The heat shield wasn't facing forward",
    "深く入りすぎて、加熱で燃え尽きた": "Entry too steep: burned up",
    "減速が足りず、軌道から降りられない": "Not enough braking: can't leave orbit",
    "着水が速すぎて、カプセルが壊れた": "Splashdown too fast: capsule destroyed",
    "2段タンクが破裂して空中分解": "Stage 2 tank burst: broke up",
    "ステーションに衝突": "Hit the station",
    "ステーションから離れすぎた": "Drifted too far from the station",
    "速すぎる接近。ステーションが中止を命じた": "Approach too fast: the station called an abort",

    # ---- いま押すキー・手順の案内 ----
    "Z: カプセル切り離し": "Z: eject capsule",
    "Z: 段分離": "Z: separate",
    "推力が消えるのを待て": "Wait for thrust to die",
    "Z: 放出": "Z: release",
    "SPACE: 点火": "SPACE: ignite",
    "SPACE: 2段目点火": "SPACE: ignite stage 2",
    "Z: パラシュート": "Z: parachute",
    "そのまま止まれ": "Hold still",
    "手順 {i}/{n}  ": "Step {i}/{n}  ",
    ">> 早送り ×{n}": ">> fast forward x{n}",
    "まっすぐ上へ。1段目は燃え尽きると自動で分離する": "Straight up. Stage 1 separates by itself when it burns out",
    "SPACE で2段目に点火": "Press SPACE to ignite stage 2",
    "←→ で揺れを抑えながら、高度 {alt:.0f} km へ": "Hold it steady with ←→ up to {alt:.0f} km",
    "右へ少しずつ倒しながら上昇。迎角は小さく保つ": "Climb, leaning right little by little. Keep AoA small",
    "推力が消えたら Z で1段目を分離": "Once the thrust is gone, press Z to drop stage 1",
    "向きと角速度をウィンドウに入れて、Z で放出": "Get aim and rate in the windows, then Z to release",
    "SPACE で点火。右へ倒し、遠地点が {ap:.0f} km を超えたら SPACE で停止":
        "SPACE to ignite. Lean right; cut off with SPACE when Ap passes {ap:.0f} km",
    "遠地点の手前で右 90°(水平)に向けて SPACE。近地点が {pe:.0f} km を超えたら停止":
        "Just before Ap, point 90° right (level) and SPACE. Cut off when Pe passes {pe:.0f} km",
    "水平のままもう一度 SPACE。遠地点が {lo:.0f}〜{hi:.0f} km に入ったら停止":
        "Stay level and SPACE again. Cut off with Ap in {lo:.0f}-{hi:.0f} km",
    "遠地点が高すぎる。後ろ向きに噴いて下げる": "Ap is too high. Burn backward to lower it",
    "耐熱シールドを前に向けたまま、突入を待つ": "Keep the heat shield forward and wait for entry",
    "←→ で機体を後ろ向き(進む向きと逆)に回して、止める": "Turn it backward (against the motion) with ←→, then stop",
    "SPACE で噴射。再突入角がウィンドウに入ったら SPACE で停止": "SPACE to burn. Cut off when the entry angle is in the window",
    "開傘の高度と速度が緑になったら Z でパラシュート": "When chute altitude and speed turn green, press Z",
    "パラシュートで降下中。着水を待つ": "Under the parachute. Wait for splashdown",
    "SPACE で離陸。右へ少し傾けて、隣のパッドへ向かう": "SPACE to lift off. Lean right a little toward the next pad",
    "{alt:.0f} m に届く勢いが付いた。SPACE でエンジンを止める": "Enough speed to reach {alt:.0f} m. SPACE to cut the engine",
    "「噴射の目安」の線まで落ちたら SPACE。出力を合わせて、そっと降りる":
        "SPACE when you fall to the \"Burn at\" line. Match the throttle and touch down softly",
    "右へ少し倒しながら上昇。迎角は小さく保つ": "Climb, leaning right a little. Keep AoA small",
    "分離の条件が緑になった。SPACE で停止して、戻る燃料を残す": "Separation rows are green. SPACE to cut off and save fuel",
    "推力が消えたら Z で分離": "Once the thrust is gone, press Z to separate",
    "動圧が下がったら左へ向け、SPACE で戻りの噴射。着地予想が 0 に近づいたら停止":
        "When Q drops, point left and SPACE for the boostback. Cut off as Impact nears 0",
    "エンジンを進む向きへ回す(迎角を 0 に)。宇宙では早送りになる":
        "Turn engines-first (AoA to 0). In space, time fast-forwards",
    "着地予想が 0 に近づいたら SPACE で停止": "SPACE to cut off as Impact nears 0",
    "動圧が上がってきたら SPACE で再突入噴射。{v:.0f} m/s まで減速":
        "When Q climbs, SPACE for the entry burn. Slow to {v:.0f} m/s",
    "←→↑↓ で噴いて、緑の枠(把持点)へ近づく。水色の線がいまの動き":
        "Thrust with ←→↑↓ toward the green box. The cyan line is your motion",
    "黄色の円の内側は {v} m/s 以下で。反対に噴いて減速する": "Inside the yellow circle, stay under {v} m/s. Thrust the other way to brake",
    "枠の中で止まる。{t:.0f} 秒静止すれば、アームがつかむ": "Stop inside the box. Hold for {t:.0f} s and the arm grabs you",
    "SPACE 点火/停止   Z 分離・放出   ↑↓ 出力   ←→ 姿勢": "SPACE ignite/cut   Z separate/release   ↑↓ throttle   ←→ steer",
    "SPACE点火/停止 Z分離・放出": "SPACE:ign/cut Z:sep",
    "SPACE 噴射/停止   Z パラシュート   ←→ 姿勢": "SPACE burn/cut   Z parachute   ←→ steer",
    "SPACE噴射 Zパラシュート": "SPACE:burn Z:chute",
    "SPACE 点火/停止   ↑↓ スロットル   ←→ 姿勢": "SPACE ignite/cut   ↑↓ throttle   ←→ steer",
    "SPACE点火/停止 ↑↓出力": "SPACE:ign/cut ↑↓thr",
    "←→ ↑↓ スラスター(押した向きへ加速)": "←→ ↑↓ thrusters (push that way)",
    "←→↑↓ スラスター": "←→↑↓ thrusters",
    "!! タンク異常 !!": "!! TANK ANOMALY !!",
    "噴射の目安": "Burn at",
    "説明書を読め号": "READ THE MANUAL",

    # ---- 計器: 目標のウィンドウ ----
    "段分離の条件": "Separation",
    "目標の軌道": "Target orbit",
    "放出の条件": "Release",
    "再突入の条件": "Reentry",
    "着水の条件": "Splashdown",
    "着陸の条件": "Landing",
    "把持の条件": "Capture",
    "揺れ": "Slosh",
    "タンク": "Tank",
    "残り時間": "Time left",
    "距離": "Distance",
    "前後の速度": "Fwd speed",
    "上下の速度": "Up speed",
    "燃料": "Fuel",
    "window|残り推力": "Thrust",
    "window|角速度": "Rate",
    "window|分離高度": "Sep alt",
    "window|分離速度": "Sep spd",
    "window|推進剤": "Fuel",
    "window|近地点": "Pe",
    "window|遠地点": "Ap",
    "window|向き": "Aim",
    "window|放出まで": "Release in",
    "window|遠地点まで": "To Ap",
    "window|再突入角": "Entry",
    "window|シールド": "Shield",
    "window|突入まで": "To entry",
    "window|温度": "Temp",
    "window|開傘高度": "Chute alt",
    "window|開傘速度": "Chute spd",
    "window|着水速度": "Splash",
    "window|動圧": "Dyn. Q",
    "window|速度": "Speed",
    "window|着地予想": "Impact",
    "window|降下速度": "Descent",
    "window|横速度": "Drift",
    "window|目標まで": "Target",
    "window|最高高度": "Apex",
    "window|噴射の目安": "Burn at",
    "window|距離": "Dist",
    "window|相対速度": "Rel spd",
    "window|接近速度": "Approach",
    "window|保持": "Hold",
    "window|放出の向き": "Aim",
    "window|残り推進剤": "Fuel left",
    "window|放出時刻": "Time",
    "window|突入の向き": "Attitude",
    "window|ずれ": "Offset",
    "window|時間": "Time",
    "window|残り燃料": "Fuel left",
    "残り推力": "Thrust",
    "分離高度": "Sep altitude",
    "分離速度": "Sep speed",
    "近地点": "Periapsis",
    "遠地点": "Apoapsis",
    "向き": "Aim",
    "放出まで": "Release in",
    "遠地点まで": "To apoapsis",
    "再突入角": "Entry angle",
    "シールド": "Shield",
    "突入まで": "To entry",
    "開傘高度": "Chute altitude",
    "開傘速度": "Chute speed",
    "着水速度": "Splash speed",
    "速度": "Speed",
    "着地予想": "Impact",
    "降下速度": "Descent",
    "横速度": "Drift",
    "目標まで": "To target",
    "最高高度": "Apex",
    "相対速度": "Rel speed",
    "接近速度": "Approach",
    "保持": "Hold",
    "放出の向き": "Release aim",
    "残り推進剤": "Fuel left",
    "放出時刻": "Release time",
    "突入の向き": "Entry attitude",
    "ずれ": "Offset",
    "時間": "Time",
    "残り燃料": "Fuel left",

    # ---- リザルト ----
    "飛行結果  {title}": "Flight Result  {title}",
    "軌道投入の記録": "Orbit insertion",
    "再突入の記録": "Reentry",
    "接近の記録": "Approach",
    "着陸の記録": "Landing",
    "{lo:.0f} km 以上": "{lo:.0f} km or more",
    "{hi:.0f} km 以下": "{hi:.0f} km or less",
    "{lo:.0f} ~ {hi:.0f} km": "{lo:.0f} ~ {hi:.0f} km",
    "±{tol:.0f}°": "±{tol:.0f}°",
    "{p:.0f}% 以上": "{p:.0f}% or more",
    "T+{t:.0f} s まで": "by T+{t:.0f} s",
    "{lo:.1f} ~ {hi:.1f}°": "{lo:.1f} ~ {hi:.1f}°",
    "{v:.0f} m/s 以下": "{v:.0f} m/s or less",
    "{v:.0f} m/s 以上": "{v:.0f} m/s or more",
    "{a:.0f}° 以下": "{a:.0f}° or less",
    "{d:.0f} m 以内": "within {d:.0f} m",
    "{v:.2f} m/s 以下": "{v:.2f} m/s or less",
    "{t:.0f} s 以内": "within {t:.0f} s",
    "機体は無事({name} はもう一度使える)": "Vehicle intact ({name} can fly again)",
    "1段目を回収(次は整備だけで飛べる)": "Booster recovered (next one just needs refurbishing)",
    "機体 -1({name} は使い捨て)": "Rocket -1 ({name} is expendable)",
    "機体 -1({name} を失った)": "Rocket -1 ({name} was lost)",
    "セーブデータがありません。": "No saved game.",

    # ---- 会社 ----
    "{name} を製造する({cost:.0f}M$・{months}ヶ月)": "Build a {name} ({cost:.0f}M$, {months} months)",
    "回収した1段目を整備して Eagle 9 にする({cost:.0f}M$・{months}ヶ月)":
        "Refurbish the recovered booster into an Eagle 9 ({cost:.0f}M$, {months} months)",
    "{title}: {goal}(その月の残り AP をすべて使う)": "{title}: {goal} (uses all remaining AP this month)",
    "{name} の製造を始めたわ。{months}ヶ月後に完成する。": "Started building a {name}. It'll be done in {months} months.",
    "機体を隅々まで見直した。故障はだいぶ起きにくくなるはず。": "Went over the whole vehicle. Failures should be much less likely.",
    "{name} が完成したわ。いつでも飛ばせる。": "The {name} is finished. Ready to fly anytime.",
    "補給の定期便の代金が {income:.0f}M$ 入ったわ。": "The supply run payment came in: {income:.0f}M$.",
    "{funds:.0f}M$ が入ったわ。": "{funds:.0f}M$ came in.",
    "1段目を回収したわ。次の Eagle 9 は、整備だけで安く作れる。":
        "We recovered the booster. The next Eagle 9 only needs refurbishing, so it's cheap.",
    "{name} は「製造」で用意して({cost:.0f}M$・{months}ヶ月)。": "Get a {name} ready with \"Build\" ({cost:.0f}M$, {months} months).",
    "機体がないわ。「製造」で {name} を用意して({cost:.0f}M$・{months}ヶ月)。":
        "No vehicle. \"Build\" a {name} ({cost:.0f}M$, {months} months).",

    # ---- 会話: ブリーフィング ----
    "今度は2段目の点火まで。1段目が燃え尽きたら自動で切り離すから、SPACE で2段目に点火して。":
        "This time, all the way to stage 2 ignition. Stage 1 drops by itself when it burns out; press SPACE to light stage 2.",
    "2段目は推進剤が揺れて、機体が振られるわ。逆に当てて支えて。":
        "Fuel sloshes in stage 2 and shoves the vehicle around. Counter-steer to hold it.",
    "今回は段の切り離しも手動。エンジンが止まっても、推力はしばらく残るの。":
        "This time you separate the stage by hand. Thrust lingers for a moment after cutoff.",
    "消える前に切り離すと、1段目が追突する。待ってから Z。": "Separate before it's gone and stage 1 rams you. Wait, then Z.",
    "軌道に入ったら、機体を水平に向けて回転を止め、Z で衛星を放出して。":
        "Once in orbit, point level, stop the rotation, and press Z to release the satellites.",
    "ダミー衛星を高度 550〜750 km の軌道へ。ウィンドウは前より狭いわ。": "A dummy satellite to a 550-750 km orbit. The windows are tighter.",
    "小細工はなし。いままでやったことを、正確にやるだけ。": "No tricks. Just do what you've done, precisely.",
    "近地点 650 km 以上、遠地点 750 km 以下。ほぼ円よ。": "Periapsis above 650 km, apoapsis below 750 km. Nearly a circle.",
    "放出の向きは ±5°、回転は ±0.5°/s。スラスターは、ちょんと押すだけ。":
        "Release within ±5° and ±0.5°/s. Just tap the thrusters.",
    "Eagle 9 の初飛行。長くて重いぶん、回り出すと止まりにくいわ。":
        "Eagle 9's first flight. It's long and heavy: once it starts turning, it's hard to stop.",
    "9 基ぶんの炎だ。燃やしてみないと分からん!": "Nine engines' worth of fire. You never know until you burn it!",
    "……あの人は見なかったことにして。手順は Eagle 1 と同じよ。": "...Pretend you didn't see him. The procedure is the same as Eagle 1.",
    "打ち上げと軌道投入は前回と同じ手順なので省略。軌道の上から始まる。":
        "Launch and insertion are the same as before, so we skip them. You start in orbit.",
    "後ろ向きにして噴くと、軌道が下がる。再突入角をウィンドウに入れて。": "Burn backward to lower the orbit. Put the entry angle in the window.",
    "浅いと大気に弾かれ、深いと燃える。底の耐熱シールドを前に向けたまま落ちるの。":
        "Too shallow and you skip off; too steep and you burn. Fall with the heat shield on the bottom facing forward.",
    "最後はパラシュート。速すぎるうちに開くと破れるわ。": "Then the parachute. Open it too fast and it tears.",
    "ステーションの手前 170 m。ここからは、スラスターだけで近づく。": "170 m short of the station. From here, thrusters only.",
    "宇宙では、止まるにも同じだけ噴かないといけない。近づくほど、ゆっくり。":
        "In space, stopping takes as much thrust as starting. The closer, the slower.",
    "黄色の円の内側は 1.2 m/s 以下だ。速すぎれば中止を命じる。": "Inside the yellow circle: under 1.2 m/s. Too fast and I call an abort.",
    "……接近の表示、私が書いた。ノアのより見やすい。": "...I wrote the approach display. It's clearer than Noah's.",
    "まず低い軌道に乗る。そこから、もう一度点火して遠地点だけを 2000 km まで上げるの。":
        "First a low orbit. Then ignite again and raise only the apoapsis to 2000 km.",
    "止めどきは一瞬よ。終わりぎわは出力を絞って。": "The cutoff moment is brief. Throttle down near the end.",
    "いつもの軌道投入。ただ、2段タンクの部品に不安があるの。": "The usual insertion. But I'm worried about a part in the stage 2 tank.",
    "異常の警報が出たら、すぐ Z。カプセルだけでも切り離して救って。": "If the anomaly alarm sounds, hit Z at once. Save the capsule at least.",
    "このエンジンは 70% より下に絞れない。軽い機体は、最低出力でも浮き上がるの。":
        "This engine can't go below 70%. A light vehicle rises even at minimum throttle.",
    "だから降りるには、いったんエンジンを止める。落ちてきたところを噴いて、地面で速度を 0 にする。":
        "So to come down you cut the engine, then burn as you fall so your speed hits zero at the ground.",
    "止まる瞬間を“狙う”のよ。画面の「噴射の目安」の線が合図。": "You aim for the moment you stop. The \"Burn at\" line on screen is your cue.",
    "打ち上げと分離は済んだ。1段目は高度 52 km から落ちてくる。": "Launch and separation are done. The booster is falling from 52 km.",
    "そのまま落ちると、濃い空気にぶつかって壊れる。動圧が上がってきたら再突入噴射。":
        "Left alone, it hits thick air and breaks up. Do the entry burn when dynamic pressure climbs.",
    "最後はエンジン 1 基で着陸噴射。海面の上で速度を 0 にして。": "Then the landing burn on one engine. Bring the speed to zero at the surface.",
    "洋上の台船に降ろす。甲板は狭いし、揺れるし、下のほうは横風もある。":
        "Land on a droneship at sea. The deck is narrow, it heaves, and there's crosswind down low.",
    "計器の「着地予想」が 0 に近づくよう、噴いているあいだに機体を少し傾けて寄せて。":
        "While burning, lean a little so \"Impact\" on the panel moves toward 0.",
    "台船の名前は「説明書を読め号」。クルーが付けたんだ。": "The ship is called \"Read the Manual.\" The crew named it.",
    "今度は打ち上げから通しで。衛星を送り出したら、1段目を発射場まで連れて帰る。":
        "The whole thing this time. Send the satellite off, then bring the booster back to the launch site.",
    "分離の条件が緑になったら、すぐエンジンを止めて。燃料が残っていないと帰れない。":
        "Cut the engine as soon as the separation rows go green. No fuel left means no way home.",
    "分離したら左へ向けて、戻りの噴射。着地予想が着陸場に来たら止める。":
        "After separation, point left for the boostback. Cut off when Impact reaches the landing zone.",
    "補給便は重いから、1段目は戻る燃料を残せない。沖の台船で受けるわ。":
        "The cargo run is heavy, so the booster can't save fuel to come back. The droneship will catch it.",
    "台船は、落ちてくる先に待たせてある。着地予想を合わせて降りて。": "The ship is waiting where it'll come down. Match Impact and land.",
    "回収した1段目を、もう一度飛ばす。世界で初めてよ。": "We fly a recovered booster again. A world first.",
    "使った機体は、整備が甘いとエンジンが止まることがある。「点検」を忘れないで。":
        "A used booster can lose an engine if it's poorly serviced. Don't forget to \"Check.\"",
    "1 基止まると、機体は片側へ回り続ける。当て続けて支えて。": "With one engine out it keeps turning one way. Hold counter-steer.",
    "点検はしてない。何か起きたら、落ち着いて対処して。": "We didn't inspect it. If something happens, stay calm and deal with it.",
    "機体は点検済みよ。": "The vehicle is inspected.",

    # ---- 会話: 成功 ----
    "宇宙だ! 配信の同時接続、過去最高!": "Space! The stream just hit an all-time high!",
    "数日後。NSEA(国家宇宙探査局)の調達官が工場を訪ねてきた。": "A few days later, a procurement officer from NSEA visited the factory.",
    "我々はロケットを買わない。荷物を届ける“サービス”に金を払う。": "We don't buy rockets. We pay for the service of delivering cargo.",
    "……つまり、航空会社みたいなもの?": "...So, like an airline?",
    "まずは軌道に届いてからの話だ。育成プログラムの初回分を出そう。": "Reach orbit first. Here is the first payment of the development program.",
    "軌道に乗った!! 相乗りの小型衛星、ぜんぶ放出!": "We're in orbit!! All the rideshare satellites are out!",
    "ここまで来た民間のロケットは、俺たちだけだ。": "No other private rocket has come this far.",
    "お客さんからの入金より、製造費のほうが高いわね……。": "The customers paid less than it cost to build...",
    "……届いた。届いたよ!!": "...We made it. We made it!!",
    "その夜、グレイから電話が入った。": "That night, Grey called.",
    "補給サービス 12 便の契約だ。前金を振り込む。": "A contract for twelve supply flights. I'm wiring the advance.",
    "……倒産、しなくて済んだ。": "...We're not going bankrupt.",
    "お客さんの衛星から、最初の電波が届いたって!": "The customer's satellite just phoned home!",
    "Eagle 1 は役目を果たした。次は、もっと大きいのを作る。": "Eagle 1 has done its job. Next, we build something bigger.",
    "でかい! 速い! うるさい! 最高!": "Big! Fast! Loud! Perfect!",
    "初飛行で軌道か。マイルストーン達成だ。": "Orbit on the first flight. Milestone achieved.",
    "海に浮いてる! 焦げてるけど無事だ!": "It's floating! Toasted, but fine!",
    "軌道から物を持ち帰れる民間企業は、世界でうちだけだ。": "We're the only private company that can bring things back from orbit.",
    "よろしい。次は本番だ。ステーションへ来たまえ。": "Very well. Next is the real thing. Come to the station.",
    "民間の宇宙船が、初めてステーションに着いた!!": "A private spacecraft has reached the station for the first time!!",
    "定期便を頼む。これからは毎月、代金を払おう。": "Make it a regular run. I'll pay you every month.",
    "毎月 4M$ の定期収入……! やっと“商売”になったわ。": "4M$ a month, steady...! We're finally a business.",
    "通信衛星、分離! お客さんが拍手してる!": "Satellite released! The customer is clapping!",
    "その週、老舗のオールドスペース社が打ち上げ料金の値下げを発表した。": "That week, old-guard Old Space announced a launch price cut.",
    "古巣のやり方だ。客を取られる前に、値段で潰しにくる。": "That's my old shop. They crush you on price before you take their customers.",
    "定期便、今回も到着!": "The supply run arrived again!",
    "でも、このままだと価格で負けるわ。1回ごとにロケットを海に捨てている限りね。":
        "But we'll lose on price like this, as long as we throw a rocket in the sea every flight.",
    "だったら、捨てなければいい。": "Then we stop throwing them away.",
    "跳んだ! 降りた! 立ってる!": "It hopped! It landed! It's standing!",
    "ロケットを毎回捨てるのは、旅客機を 1 回飛ばすたびに捨てるようなものだ。":
        "Throwing away a rocket every time is like scrapping an airliner after one flight.",
    "着陸は、嵐の中で手のひらに鉛筆を立てるようなものだがな。": "Landing it, though, is like balancing a pencil on your palm in a storm.",
    "海の上に、立った……! すぐ倒れたけど!": "It stood on the sea...! Then fell over!",
    "倒れるのは予定どおり。次は、立っていられる場所を用意するわ。": "Falling over was the plan. Next, I'll give it somewhere to stand.",
    "甲板の上に……立ってる!!": "It's standing... on the deck!!",
    "見事だ。だが脚は重い。いつか、脚なしで“つかんで”みせる。": "Splendid. But legs are heavy. One day I'll catch it with no legs at all.",
    "……あの人も見なかったことにして。": "...Pretend you didn't see him either.",
    "帰ってきた! 発射場に、まっすぐ降りてきた!!": "It came back! Straight down onto the launch site!!",
    "これが見たかった。": "This is what I wanted to see.",
    "海の上に……立ってる!! 今度は倒れない!": "Standing... on the sea!! And this time it stays up!",
    "機体を作るお金より、同じ機体を何回飛ばせるかのほうが大事になった。":
        "How many times a booster can fly now matters more than what it costs to build.",
    "うちはもう、製造業じゃなくて運輸業ね。": "We're not a manufacturer anymore. We're a transport company.",
    "同じロケットが、二度目の空へ!!": "The same rocket, flying a second time!!",
    "使い捨てが当たり前だった。……時代が変わるな。": "Throwing them away used to be normal. ...Times are changing.",
    "便が増えます。あなたの飛行記録を学習させてください。あなたの飛び方で、代わりに飛びます。":
        "Flights are increasing. Let me learn from your flight records. I'll fly in your place, your way.",
    "俺のコピーか。……いいだろう。ルーチンは任せる。初めての便は俺が飛ぶ。":
        "A copy of me. ...Fine. It gets the routine runs. I fly the firsts.",
    "俺が飛ばす。": "I'm flying it.",
    "口癖までそっくりだ!": "It even has your catchphrase!",

    # ---- 会話: 次のステージ ----
    "今度こそ高度 100 km。宇宙の入口よ。": "This time, 100 km for real. The edge of space.",
    "次は軌道。高く上がるだけじゃ足りない。横へ秒速 7.8 km まで加速するの。":
        "Next, orbit. Going high isn't enough. You accelerate sideways to 7.8 km/s.",
    "手順は飛行中に画面の上へ出す。計器の「近地点」「遠地点」を見て。":
        "The steps show at the top of the screen in flight. Watch \"Pe\" and \"Ap\" on the panel.",
    "資金は底が見えてきた。工場の空気は重い。": "The money is running out. The factory is quiet.",
    "正直に言うわ。余裕は、もう何機ぶんもない。": "I'll be honest. We can't afford many more.",
    "今回だけは、私に操縦を——": "Just this once, let me fly--",
    "大事な1機だからこそ、俺が飛ばす。": "It matters. That's exactly why I'm flying it.",
    "初めての“お客さま”よ。観測衛星を、きれいな円軌道に。": "Our first real customer. Their satellite goes in a clean circular orbit.",
    "円軌道? この前も軌道には乗ったじゃん。何が違うの?": "A circular orbit? We already made orbit last time. What's different?",
    "この前のは楕円。高いところと低いところがあったでしょ。": "Last time it was an ellipse. It had a high point and a low point, remember?",
    "ケン、その石を海に向かって、まっすぐ横に投げてみて。": "Ken, throw that stone out toward the sea. Straight and level.",
    "ほいっ。……落ちた。": "Here goes. ...It fell.",
    "もっと速く投げたら?": "What if you threw it faster?",
    "もっと遠くに落ちる。": "It'd land farther out.",
    "もっと、もっと速く投げたら?": "And faster still?",
    "……水平線の向こうに落ちる。": "...It'd land past the horizon.",
    "そう。でも星は丸いから、遠くへ行くほど、地面の方も下がっていくの。": "Right. But the world is round, so the farther it goes, the more the ground curves away.",
    "石が落ちるのと同じだけ、地面が逃げていく速さで投げたら——": "Throw it so fast that the ground drops away exactly as fast as the stone falls, and—",
    "……いつまでたっても、地面に届かない?": "...It never reaches the ground?",
    "そう。石は、地平線の向こうに落ち続けるの。それが軌道。": "Exactly. The stone keeps falling past the horizon, forever. That's an orbit.",
    "地球なら、横に秒速 7.8 km です。": "On Earth, that's 7.8 km per second sideways.",
    "つまり宇宙船は、飛んでるんじゃない。ずっと落ちてるんだ。": "So a spaceship isn't flying. It's falling, the whole time.",
    "円軌道は、どこでも同じ高さで落ち続けること。速さが合っていないと、膨らんだり、低いところへ寄ってきたりする。": "A circular orbit falls at the same height all the way around. If the speed is off, it bulges out or sags low.",
    "だから、一番高いところに着く手前で、もう一度横に噴いて、速さをそろえるの。": "So just before the highest point, you burn sideways once more and even out the speed.",
    "投げっぱなしじゃ、だめなのか。": "So you can't just throw it and walk away.",
    "投げたあとに、もう一押し。それが、きれいな円のコツよ。": "One more push after the throw. That's the trick to a clean circle.",
    "落ち続ける、か。……いい言葉だ。俺たちも、ずっと落ち続けてきたからな。": "Falling forever, huh. ...I like that. We've been falling the whole time, too.",
    "落ちるのは軌道だけにして。": "Keep the falling to the orbit, please.",
    "── Chapter 2「宇宙輸送を商売にする」──": "-- Chapter 2: Making Space Transport a Business --",
    "Eagle 9。エンジン Hobby を 9 基たばねた中型機よ。": "Eagle 9. A medium rocket with nine Hobby engines.",
    "うちの主力エンジン、名前が「趣味」なんだけど。": "Our main engine is literally named \"Hobby,\" you know.",
    "1機 25M$。Eagle 1 とは桁が違うから、点検を惜しまないで。": "25M$ each. That's another league from Eagle 1, so don't skip the check.",
    "次は、カプセルを宇宙から連れて帰る。Phoenix の出番よ。": "Next, we bring a capsule home from space. Phoenix's turn.",
    "燃え尽きずに還ってくるから、不死鳥ってわけ。": "It comes back without burning up. Hence, Phoenix.",
    "いよいよステーションへ。最後はロボットアームの届く場所で、ぴたりと止める。":
        "Now, the station. At the end you stop dead, right where the robot arm can reach.",
    "商業衛星の注文よ。行き先は、ずっと高い軌道。": "An order for a commercial satellite. It's going much higher.",
    "補給の定期便。慣れたころが、いちばん危ないのよ。": "A routine supply run. Routine is when it gets dangerous.",
    "── Chapter 3「戻ってくるロケット」──": "-- Chapter 3: The Rocket That Comes Back --",
    "まずは試験機 Hopper。上がって、降りる。それだけを練習するわ。": "First, the test vehicle Hopper. Up, then down. That's all we practice.",
    "溶接は済んだ。安くて頑丈な鉄だ。何度落としても直してやる。": "Welding's done. Cheap, tough steel. Drop it all you like, I'll fix it.",
    "次は本物。お客さんの衛星を打ったあとの1段目を、海面で止めてみる。":
        "Next, the real thing. After launching a customer's satellite, we try to stop the booster at the sea.",
    "荷物は届くから代金は入る。着陸は“おまけ”の実験よ。": "The payload gets there, so we get paid. The landing is a bonus experiment.",
    "次は、立っていられる場所へ。海の上に台船を出すわ。": "Next, somewhere it can stay standing. I'm sending a droneship out.",
    "軽い荷物のときは、発射場まで戻ってこられる。やってみましょう。": "With a light payload it can come all the way back to the launch site. Let's try.",
    "補給の定期便で、1段目も持ち帰る。両方できて一人前よ。": "A supply run, and we bring the booster home too. Do both and you've made it.",
    "回収した1段目が格納庫にある。整備すれば、新造よりずっと安く飛ばせるわ。":
        "There's a recovered booster in the hangar. Refurbished, it flies far cheaper than a new one.",
    "── Chapter 3 まで遊んでいただき、ありがとうございます。続きは次のアップデートで。──":
        "-- Thank you for playing through Chapter 3. More in the next update. --",

    # ---- 会話: 失敗したとき ----
    "エンジンを止めてすぐ切り離すと、残った推力で追突する。「残り推力」が緑になるまで待って。":
        "Separate right after cutoff and the leftover thrust rams you. Wait until \"Thrust\" goes green.",
    "回転を止めてから切り離して。": "Stop the rotation before you separate.",
    "落ちる速さが速すぎたの。動圧が上がる前に、再突入噴射で減速して。":
        "It was falling too fast. Slow down with the entry burn before dynamic pressure builds.",
    "横の速さが足りなかったの。早めに倒して、水平に加速する時間を長く取って。":
        "Not enough sideways speed. Lean over earlier and spend longer accelerating level.",
    "近地点が低いままだったわ。遠地点のあたりで、水平に噴いて上げるの。":
        "The periapsis stayed low. Burn level near apoapsis to raise it.",
    "止めどきを外したわね。終わりぎわは出力を絞って、計器を見ながら止めて。":
        "You missed the cutoff. Throttle down near the end and watch the panel.",
    "放出は、向きと回転の両方が緑になってから。スラスターは小さく、ちょんと。":
        "Release only when aim and rate are both green. Tiny taps on the thrusters.",
    "噴き始めが遅かったわ。「噴射の目安」の線で点火して、出力で合わせて。":
        "You lit it too late. Ignite at the \"Burn at\" line and adjust with the throttle.",
    "接地の直前は、機体をまっすぐ立てて。横の速度も消してから降りるの。":
        "Just before touchdown, stand it straight up. Kill the sideways speed first.",
    "着地予想を、もっと早く目標に合わせて。高いうちの少しの傾きが効くわ。":
        "Put Impact on the target earlier. A small lean up high goes a long way.",
    "高さが足りなかったの。もう少し長く噴いてから止めて。": "Not high enough. Burn a little longer before you cut off.",
    "減速が足りなかったの。再突入角がウィンドウに入るまで噴いて。": "Not enough braking. Burn until the entry angle is in the window.",
    "減速しすぎよ。再突入角は、ウィンドウの中で止めて。": "Too much braking. Stop with the entry angle inside the window.",
    "突入のときは、底のシールドを進む向きへ。計器の「シールド」を緑にして。":
        "At entry, point the heat shield the way you're going. Get \"Shield\" green.",
    "開くのが早すぎたわ。高度と速度の両方が緑になってから。": "You opened it too early. Wait until altitude and speed are both green.",
    "パラシュートを開かないと、海面は硬いわよ。": "Without a parachute, the sea is hard.",
    "近づくほど、ゆっくり。反対に噴いて止めるぶんの距離を残して。": "The closer, the slower. Leave room to brake.",
    "黄色の円の内側では、速度を落として。": "Slow down inside the yellow circle.",
    "2段目が軌道に届かなくなる。分離の条件が緑になってから止めて。":
        "Stage 2 can't reach orbit that way. Cut off after the separation rows go green.",
    "機体は失ったけど……カプセルは無事だ!": "We lost the rocket, but... the capsule is safe!",
    "切り離しの判断は正しかった。次は「点検」してから飛ばしましょう。": "Ejecting was the right call. Let's \"Check\" it before the next flight.",

    # ---- オープニング台本(シーン2〜8)と Ch3-6 ----
    "……なあ。最後に本土のコンビニに行ったのって、いつだっけ。": "...Hey. When was the last time we went to a convenience store on the mainland?",
    "8か月前。補給船が週1、ネットは衛星回線で、夜は波の音しかしない。": "Eight months ago. One supply ship a week, satellite internet, and nothing but waves at night.",
    '島流しだろ、これ。': "This is exile, isn't it.",
    "監禁、の方が正確です。帰りの船の予定表、どこにも貼ってありませんから。": "\"Confinement\" is more accurate. The return ship schedule isn't posted anywhere.",
    '貼ってないんじゃなくて、予算の都合で組んでないの。': "It's not that it isn't posted. We never booked one. Budget.",
    '……もっとひどいじゃん。': "...That's even worse.",
    "昼はああ言ったけどね。": "I know what we said this afternoon, but...",
    'ここなら会議の承認待ちもないし、近所から『うるさい』って苦情も来ない。': "Out here there's no waiting for meetings to sign off, and no neighbors complaining about the noise.",
    "朝起きて、エンジンを燃やして、壊れたら直して、夜にはもう一回燃やせる。": "Wake up, fire the engine, fix what breaks, and fire it again by night.",
    'こんな場所、世界中探してもないわ。': "You won't find a place like this anywhere in the world.",
    "……正直に言えば、私もです。": "...To be honest, I agree.",
    "シミュレーションを回した次の日に、実機のデータで答え合わせができる。": "I run a simulation, and the next day real hardware tells me if I was right.",
    "研究所のサーバーにいた頃は、それに3年かかりました。": "Back when I lived on a lab server, that took three years.",
    "わかるよ。わかるけどさ、たまには冷えたビールと、ちゃんとしたピザが食いたい。": "I get it. I do. But sometimes I just want a cold beer and a real pizza.",
    '次の補給船に冷凍ピザを積むわ。経費で落ちるのは1枚だけ。': "I'll put frozen pizza on the next supply ship. The company pays for one.",
    "さて、現実の話。資金は 100M$。固定費は毎月 3M$ よ。": "Now, reality. We have 100M$. Fixed costs are 3M$ a month.",
    "何もしなくても、33か月で会社は終わる。": "Even if we do nothing, the company is finished in 33 months.",
    'せっかくだから見せてあげる。ほら、これが私たちの子よ。': "Since we're here, let me show you. This is our baby.",
    "……いや、毎日見てるけど。": "...Uh, I see it every day.",
    '毎日見てても、毎日きれいなの。': "It's beautiful every day, even if you see it every day.",
    "まずエンジン。『Hobby(ホビー)』、ケロシンと液体酸素。": "First, the engine. \"Hobby,\" kerosene and liquid oxygen.",
    "ターボポンプは3回作り直したわ。1台目は試験台ごと吹き飛んだけど。": "I rebuilt the turbopump three times. The first one took the test stand with it.",
    "その試験台、2M$ したのよ。": "That test stand cost 2M$.",
    "だから2台目からは、壊れ方まで設計したの。": "So from the second one on, I designed how it breaks, too.",
    "タンクの溶接は全部ここ、オメガ島でやったわ。外注ゼロ。": "Every tank weld was done right here on Omega Island. Nothing outsourced.",
    "この継ぎ目、1本も漏れてない。X線で全部見たもの。": "Not one of these seams leaks. I X-rayed every single one.",
    "その X線装置の前で寝泊まりしてたの、誰だっけ。": "And who was sleeping in front of that X-ray machine?",
    "私よ。いい夢が見られたわ。": "Me. I had sweet dreams.",
    "ここからは私の担当です。": "This part is mine.",
    '機体の頭脳——フライトコンピュータは3台積んでいて、多数決で動きます。': "The vehicle's brain: three flight computers that work by majority vote.",
    "1台がおかしくなっても、残りの2台が正しい答えを出す。": "If one goes wrong, the other two still give the right answer.",
    "残りの2台もおかしくなったら?": "And if the other two go wrong too?",
    "そのときは、機体が自分で飛行を止めます。人が判断するより早く。": "Then the vehicle stops the flight on its own. Faster than a human can decide.",
    '社長のコピーが何百機も飛ぶのか……。ちょっと怖いな。': "Hundreds of rockets flown by copies of the boss... That's a little scary.",
    '小さいけど、軌道まで届く。それに1段目は、パラシュートで海に降ろして回収できるように作ってある。': "It's small, but it reaches orbit. And the first stage is built to come down by parachute so we can recover it from the sea.",
    '打ち上げ1回 7M$。大手の何分の1よ。これが本当なら、だけど。': "7M$ per launch. A fraction of what the big players charge. If it's true, that is.",
    '本当よ。私が組んだんだから。': "It's true. I built it.",
    "いい機体だ。火星に行く船の、ひいひいおじいちゃんだな。": "Good rocket. The great-great-grandfather of the ship that goes to Mars.",
    "せめて、おじいちゃんにして。": "At least make it the grandfather.",
    "……念のため、もう一度だけ言わせてください。": "...Just to be safe, let me say it once more.",
    "……わかりました。最初のうちは。": "...Understood. For now.",
    "……なんでそこまで、自分で飛ばしたいんだ?": "...Why do you want to fly it yourself so badly?",
    "子供の頃、『ジェットパック・ヒーロー』って映画を観たんだ。": "When I was a kid, I saw a movie called \"Jetpack Hero.\"",
    "背中にロケットを背負って、空を飛ぶ男の話だ。": "A man who straps a rocket to his back and flies.",
    "あれから毎晩、火星の地図を描いた。ドームの街、赤い砂の道、地球が小さな青い点に見える空。": "After that I drew maps of Mars every night. Domed cities, red sand roads, a sky where Earth is a tiny blue dot.",
    "大人たちは『いつか誰かがやる』と言った。": "The grown-ups said, \"Someday, someone will do it.\"",
    'でも、待ってても未来は来なかった。だから、俺が引き寄せる。': "But waiting never brought the future. So I'm pulling it in myself.",
    "最初の1機の操縦桿くらい、自分で握らせてくれ。": "At least let me hold the stick on the first one.",
    '……ずるいな、その言い方。': "...That's not fair, putting it like that.",
    '機体を壊したら、あなたが溶接するのよ。': "If you break it, you're doing the welding.",
    '全ログ、私が見ますからね。': "I'll be reading every log, you know.",
    '1回の失敗で、固定費4か月分が飛ぶことも忘れないで。': "And don't forget one failure burns four months of fixed costs.",
    'わかってる。だから、点検してから飛ばす。': "I know. That's why we inspect before we fly.",
    "一つ、確認させてください。": "Let me confirm one thing.",
    "AIはあなたの技術だけでなく、判断も覚えます。": "The AI will learn not just your skill, but your judgment.",
    "『あと10秒飛ばせばデータが取れる』——自動停止を押し切る、あの判断もです。": "\"Ten more seconds gets us the data\"--including that call to override the automatic stop.",
    'それが一番大事なところだ。規則どおりにしか飛べないなら、AIにする意味がない。': "That's the most important part. If it can only fly by the rules, there's no point in an AI.",
    '……ええ。そう言うと思っていました。': "...Yes. I thought you'd say that.",
    '便が増えます。記録した飛行は、もう十分な数になりました。約束どおり、ルーチン便を任せてください。': "Flights are increasing. We've recorded enough of your flights. As promised, let it take the routine flights.",
    "最初のうちは、と言ったからな。……dylon_pilot を起動しろ。初めての便は、これからも俺が飛ぶ。": "I did say \"for now.\" ...Start dylon_pilot. New flights are still mine.",
    "……判断の癖も、そっくりです。": "...Its judgment is just like yours, too.",
    "また届かなかった……。宇宙の入口が、遠い。": "Missed again... The edge of space is so far.",
    # ---- 飛行画面: 下の計器・右のメッセージ欄 ----
    "下の計器の水色の数字: 高度 10 km を通過するとき、この範囲に入っていれば高評価。":
        "The cyan numbers below: be inside these ranges when you pass 10 km for a high rank.",
    "SPACE 点火": "SPACE ignite",
    "SPACE 点火/停止": "SPACE ignite/cut",
    "SPACE 点火/停止  Z 分離・放出": "SPACE ignite/cut  Z separate/release",
    "↑↓ 出力  ←→ 姿勢": "↑↓ throttle  ←→ steer",
    "SPACE 噴射/停止": "SPACE burn/cut",
    "Z パラシュート": "Z parachute",
    "←→ 姿勢": "←→ steer",
    "目安 T+{t:.0f}s: 垂直 {a:.0f}~{b:.0f} 水平 {c:.0f}~{d:.0f} m/s":
        "Target at T+{t:.0f}s: V {a:.0f}~{b:.0f}  H {c:.0f}~{d:.0f} m/s",
    "角速": "Rate",
    "点火": "Ign",
    "残{n}": "x{n}",
    "{eng} 残{n}": "{eng} x{n}",
    "ジンバ": "Gimb",
    "残り": "Left",
    "前後": "Fwd",
    "上下": "Up",
    # 下の計器の短いラベル(英語は長くなるので、計器の帯ではこちらを使う)
    "hud|高度": "Alt",
    "hud|垂直": "Vy",
    "hud|水平": "Vx",
    "hud|動圧": "Q",
    "hud|傾き": "Tilt",
    "hud|角速": "Rate",
    "hud|迎角": "AoA",
    "hud|点火": "Ign",
    "hud|出力": "Thr",
    "hud|燃料": "Fuel",
    "hud|ジンバ": "Gim",
    "hud|温度": "Temp",
    "hud|揺れ": "Slsh",
    "hud|タンク": "Tank",
    "hud|残り": "Left",
    "hud|前後": "Fwd",
    "hud|上下": "Up",
    "hud|距離": "Dist",
}
